# Generated by Django 4.0 on 2021-12-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('std_id', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('std_id',),
            },
        ),
    ]
